"""initial migration

Revision ID: 1f5f4a85b791
Revises: 
Create Date: 2025-09-12 10:58:19.807974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5f4a85b791'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('budget_category', sa.String(length=50), nullable=True),
    sa.Column('lifestyle_category', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('settlement_type', sa.String(length=50), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('image2', sa.String(length=500), nullable=True),
    sa.Column('image3', sa.String(length=500), nullable=True),
    sa.Column('image4', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('budget_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_budget_category'), 'ai_recommendations', ['budget_category'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_budget_score'), 'ai_recommendations', ['budget_score'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_category'), 'ai_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_created_at'), 'ai_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_destination_type'), 'ai_recommendations', ['destination_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_lifestyle_category'), 'ai_recommendations', ['lifestyle_category'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_location'), 'ai_recommendations', ['location'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_name'), 'ai_recommendations', ['name'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_popularity'), 'ai_recommendations', ['popularity'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_rating'), 'ai_recommendations', ['rating'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_settlement_type'), 'ai_recommendations', ['settlement_type'], unique=False)
    op.create_table('saved_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_places_id'), 'saved_places', ['id'], unique=False)
    op.create_index(op.f('ix_saved_places_rec_id'), 'saved_places', ['rec_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cancelled', name='tripstatus'), nullable=True),
    sa.Column('budget_range', sa.Enum('low', 'medium', 'high', 'luxury', name='budgetrange'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('means', sa.String(), nullable=True),
    sa.Column('cost_estimated', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('local_gov', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('yearly_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yearly_budget_id'), 'yearly_budget', ['id'], unique=False)
    op.create_index(op.f('ix_yearly_budget_year'), 'yearly_budget', ['year'], unique=True)
    op.create_table('active_trip_ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('rec_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cultural_tips', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('best_time', sa.String(length=80), nullable=True),
    sa.Column('estimated_cost', sa.String(length=80), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('in_itinerary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_trip_ai_recommendations_category'), 'active_trip_ai_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_created_at'), 'active_trip_ai_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_destination'), 'active_trip_ai_recommendations', ['destination'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_id'), 'active_trip_ai_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_popularity'), 'active_trip_ai_recommendations', ['popularity'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_rec_id'), 'active_trip_ai_recommendations', ['rec_id'], unique=True)
    op.create_index(op.f('ix_active_trip_ai_recommendations_title'), 'active_trip_ai_recommendations', ['title'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_trip_id'), 'active_trip_ai_recommendations', ['trip_id'], unique=False)
    op.create_index(op.f('ix_active_trip_ai_recommendations_user_id'), 'active_trip_ai_recommendations', ['user_id'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_id'), 'itineraries', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_itineraries_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_user_id'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_trip_id'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_title'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_rec_id'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_popularity'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_id'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_destination'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_created_at'), table_name='active_trip_ai_recommendations')
    op.drop_index(op.f('ix_active_trip_ai_recommendations_category'), table_name='active_trip_ai_recommendations')
    op.drop_table('active_trip_ai_recommendations')
    op.drop_index(op.f('ix_yearly_budget_year'), table_name='yearly_budget')
    op.drop_index(op.f('ix_yearly_budget_id'), table_name='yearly_budget')
    op.drop_table('yearly_budget')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_saved_places_rec_id'), table_name='saved_places')
    op.drop_index(op.f('ix_saved_places_id'), table_name='saved_places')
    op.drop_table('saved_places')
    op.drop_index(op.f('ix_ai_recommendations_settlement_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_rating'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_popularity'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_name'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_location'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_lifestyle_category'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_destination_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_created_at'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_category'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_budget_score'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_budget_category'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
